name: ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.mjs"
      - "**/*.ts"
      - "**/*.css"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: lint typecheck
        run: pnpm run lint:type-check
      - name: cache lint js
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: node_modules/.cache/eslint
          key: lint-js-v1-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            lint-js-v1-
      - name: lint js
        run: pnpm run lint --cache-strategy content --cache-location node_modules/.cache/eslint/
      - name: lint css
        run: pnpm run lint:css

  css:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Cache Playwright Browsers
        uses: ./.github/actions/cache-playwright
        id: playwright-cache
        with:
          working-directory: .
      - name: Setup project
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm run setup
      - name: Build storybook for css
        run: pnpm run css storybook:build
      - name: Serve Storybook and run tests for css
        run: |
          pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm run css storybook:preview --port 6006 --silent" \
            "pnpm dlx wait-on tcp:127.0.0.1:6006 && pnpm run css storybook:test"
      - name: Unit tests for css
        run: pnpm css test
      - name: Build for css
        run: pnpm css build

  vue:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Cache Playwright Browsers
        uses: ./.github/actions/cache-playwright
        id: playwright-cache
        with:
          working-directory: .
      - name: Setup project
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm run setup
      - name: Unit tests for vue
        run: pnpm vue test
      - name: Build for vue
        run: pnpm vue build
